[package]
name = "yaml-to"
version = "0.1.0"
authors = ["Rob Rowe <rippinrobr@hotmail.com>"]
edition = "2018"

[dependencies]
barrel = { path = "../barrel", features = ["pg", "sqlite3", "mysql"]}
serde_yaml = "0.8.8"
serde = "1.0"
serde_derive = "1.0"
